language: node_js
node_js:
  - "5.2"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy  ifit-8e49f 1/a_jOX4K2aCmUaeYQlJY2lCOo1TqhpaB-6AKp_4mOBWyzfXRL-nCESHh4fwdXvVrh